version: '2'
volumes:
  pulse:                          # Only required if using PA over UNIX socket

services:
  browser:
    image: balenablocks/browser
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    ports:
        - '5011' # management API (optional)
        - '35173' # Chromium debugging port (optional)
    environment:
      LAUNCH_URL: http://www.google.com
      SHOW_CURSOR: 1
    volumes:
      - 'pulse:/run/pulse'
  fbcp:
    build: ./fbcp
    privileged: true
    environment:
      FBCP_DISPLAY: waveshare32b
  audio:
    image: balenablocks/audio
    privileged: true
    # labels:
    #   io.balena.features.dbus: 1  # Only required for bluetooth support
    # ports:
    #   - 4317:4317                 # Only required if using PA over TCP socket
    volumes:
      - 'pulse:/run/pulse'        # Only required if using PA over UNIX socket
